from folge1 import getFolgenInhalt, isValid

def mulder1():
 contentMulder = [getFolgenInhalt("urn:cts:xfiles:s1.1X01:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X02:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X03:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X04:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X05:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X06:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X07:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X08:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X09:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X10:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X11:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X12:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X13:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X14:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X15:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X16:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X17:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X18:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X19:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X20:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X21:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X22:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X23:1", " MULDER", "")]
 f = open("mulder1", "w")
 f.write("\n".join(contentMulder))
 f.flush
 f.close
	
def scully1():
 contentScully = [getFolgenInhalt("urn:cts:xfiles:s1.1X01:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X02:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X03:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X04:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X05:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X06:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X07:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X08:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X09:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X10:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X11:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X12:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X13:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X14:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X15:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X16:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X17:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X18:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X19:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X20:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X21:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X22:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s1.1X23:1", " SCULLY", "")]
 f = open("scully1", "w")
 f.write("\n".join(contentScully))
 f.flush
 f.close
# return "\n".join(contentScully)
 
def scully2():
 contentScully = [getFolgenInhalt("urn:cts:xfiles:s2.2X01:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X02:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X03:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X04:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X05:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X06:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X07:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X08:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X09:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X10:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X11:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X12:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X13:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X14:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X15:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X16:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X17:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X18:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X19:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X20:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X21:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X22:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X23:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X24:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X25:1", " SCULLY", "")]
 f = open("scully2", "w")
 f.write("\n".join(contentScully))
 f.flush
 f.close
 #return "\n".join(contentScully)
	                
def mulder2():
 contentMulder = [getFolgenInhalt("urn:cts:xfiles:s2.2X01:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X02:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X03:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X04:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X05:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X06:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X07:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X08:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X09:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X10:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X11:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X12:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X13:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X14:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X15:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X16:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X17:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X18:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X19:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X20:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X21:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X22:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X23:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X24:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s2.2X25:1", " MULDER", "")]
 f = open("mulder2", "w")
 f.write("\n".join(contentMulder))
 f.flush
 f.close
 #return "\n".join(contentMulder)
 
def scully3():
 contentScully = [getFolgenInhalt("urn:cts:xfiles:s3.3X01:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X02:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X03:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X04:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X05:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X06:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X07:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X08:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X09:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X10:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X11:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X12:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X13:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X14:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X15:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X16:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X17:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X18:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X19:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X20:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X21:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X22:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X23:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X24:1", " SCULLY", "")]
 f = open("scully3", "w")
 f.write("\n".join(contentScully))
 f.flush
 f.close
 #return "\n".join(contentScully)
	                
def mulder3():
 contentMulder = [getFolgenInhalt("urn:cts:xfiles:s3.3X01:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X02:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X03:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X04:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X05:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X06:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X07:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X08:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X09:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X10:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X11:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X12:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X13:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X14:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X15:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X16:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X17:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X18:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X19:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X20:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X21:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X22:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X23:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s3.3X24:1", " MULDER", "")]
 f = open("mulder3", "w")
 f.write("\n".join(contentMulder))
 f.flush
 f.close
 #return "\n".join(contentMulder)  

def scully4():
 contentScully = [getFolgenInhalt("urn:cts:xfiles:s4.4X01:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X02:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X03:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X04:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X05:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X06:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X07:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X08:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X09:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X10:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X11:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X12:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X13:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X14:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X15:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X16:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X17:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X18:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X19:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X20:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X21:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X22:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X23:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X24:1", " SCULLY", "")]
 f = open("scully4", "w")
 f.write("\n".join(contentScully))
 f.flush
 f.close
 #return "\n".join(contentScully)
	                
def mulder4():
 contentMulder = [getFolgenInhalt("urn:cts:xfiles:s4.4X01:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X02:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X03:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X04:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X05:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X06:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X07:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X08:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X09:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X10:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X11:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X12:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X13:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X14:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X15:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X16:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X17:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X18:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X19:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X20:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X21:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X22:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X23:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s4.4X24:1", " MULDER", "")]
 f = open("mulder4", "w")
 f.write("\n".join(contentMulder))
 f.flush
 f.close
 #return "\n".join(contentMulder)  
 
def scully5():
 contentScully =  [getFolgenInhalt("urn:cts:xfiles:s5.5X01:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X02:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X03:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X04:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X05:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X06:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X07:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X08:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X09:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X10:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X11:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X12:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X13:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X14:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X15:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X16:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X17:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X18:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X19:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X20:1", " SCULLY", "")]
 f = open("scully5", "w")
 f.write("\n".join(contentScully))
 f.flush
 f.close
# return "\n".join(contentScully)
	                
def mulder5():
 contentMulder = [getFolgenInhalt("urn:cts:xfiles:s5.5X01:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X02:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X03:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X04:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X05:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X06:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X07:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X08:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X09:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X10:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X11:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X12:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X13:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X14:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X15:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X16:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X17:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X18:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X19:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s5.5X20:1", " MULDER", "")]
 f = open("mulder5", "w")
 f.write("\n".join(contentMulder))
 f.flush
 f.close
 #return "\n".join(contentMulder)
 
def scully6():
 contentScully = [getFolgenInhalt("urn:cts:xfiles:s6.6X01:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X02:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X03:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X04:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X05:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X06:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X07:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X08:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X09:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X10:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X11:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X12:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X13:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X14:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X15:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X16:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X17:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X18:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X19:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X20:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X21:1", " SCULLY", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X22:1", " SCULLY", "")]
 f = open("scully6", "w")
 f.write("\n".join(contentScully))
 f.flush
 f.close
 #return "\n".join(contentScully)

def mulder6():
 contentMulder = [getFolgenInhalt("urn:cts:xfiles:s6.6X01:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X02:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X03:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X04:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X05:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X06:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X07:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X08:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X09:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X10:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X11:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X12:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X13:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X14:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X15:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X16:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X17:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X18:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X19:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X20:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X21:1", " MULDER", "")
	                ,getFolgenInhalt("urn:cts:xfiles:s6.6X22:1", " MULDER", "")]
 f = open("mulder6", "w")
 f.write("\n".join(contentMulder))
 f.flush
 f.close
 #return "\n".join(contentMulder)

#print(mulder1())
scully1()
scully2()
scully3()
scully4()
scully5()
scully6()

mulder1()
mulder2()
mulder3()
mulder4()
mulder5()
mulder6()
